# Generated by Django 2.2.7 on 2020-01-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20191229_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='chest_pain',
            field=models.PositiveSmallIntegerField(choices=[(0, 'None'), (1, 'Low'), (2, 'Medium'), (3, 'Severe')], default=1),
        ),
    ]
