# Generated by Django 2.2.7 on 2020-01-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofileinfo_chest_pain'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='cholestrol',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='diastolic_bp',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='glucose',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='systolic_bp',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
