# Generated by Django 2.2.7 on 2020-05-03 11:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveSmallIntegerField()),
                ('bmi', models.FloatField()),
                ('glucose', models.PositiveSmallIntegerField(default=0)),
                ('cholestrol', models.FloatField(default=0)),
                ('pregnancies', models.PositiveSmallIntegerField(default=0)),
                ('skin_thickness', models.FloatField(default=0)),
                ('systolic_bp', models.PositiveSmallIntegerField(default=0)),
                ('diastolic_bp', models.PositiveSmallIntegerField(default=0)),
                ('hypertension', models.PositiveSmallIntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('chest_pain', models.PositiveSmallIntegerField(choices=[(0, 'None'), (1, 'Low'), (2, 'Medium'), (3, 'Severe')], default=0)),
                ('generation_date', models.DateField(blank=True)),
                ('exang', models.PositiveSmallIntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('fbs', models.PositiveSmallIntegerField(default=0)),
                ('rest_ecg', models.PositiveSmallIntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High')], default=0)),
                ('residence_type', models.PositiveSmallIntegerField(choices=[(0, 'Rural'), (1, 'Urban')], default=0)),
                ('slope', models.PositiveSmallIntegerField(default=0)),
                ('ca', models.PositiveSmallIntegerField(default=0)),
                ('thal', models.PositiveSmallIntegerField(default=0)),
                ('heart_disease', models.PositiveSmallIntegerField(blank=True)),
                ('diabetes', models.PositiveSmallIntegerField(blank=True)),
                ('stroke', models.PositiveSmallIntegerField(blank=True)),
                ('user', models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
