# Generated by Django 2.2.7 on 2020-05-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_adv_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='bmi',
            field=models.FloatField(blank=True),
        ),
    ]
