# Generated by Django 2.2.7 on 2020-05-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_adv_app', '0002_auto_20200503_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='diabetes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='generation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='heart_disease',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='stroke',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
