# Generated by Django 2.2.7 on 2020-05-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_adv_app', '0003_auto_20200503_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='skin_thickness',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
