# Generated by Django 2.2.7 on 2020-05-27 07:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('health_adv_app', '0004_auto_20200505_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-generation_date']},
        ),
        migrations.RemoveField(
            model_name='report',
            name='ca',
        ),
        migrations.RemoveField(
            model_name='report',
            name='slope',
        ),
        migrations.RemoveField(
            model_name='report',
            name='thal',
        ),
        migrations.AlterField(
            model_name='report',
            name='generation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='report',
            name='heart_disease',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
