# Generated by Django 2.2.7 on 2020-05-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_adv_app', '0005_auto_20200527_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='bp_plot',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='report',
            name='cholestrol_plot',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='report',
            name='glucose_plot',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
