# Generated by Django 2.2.7 on 2020-05-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_adv_app', '0006_auto_20200527_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='weight_plot',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
