# Generated by Django 2.2.7 on 2020-05-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_adv_app', '0008_auto_20200528_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='glucose_plot',
            field=models.ImageField(blank=True, upload_to='images/plots/'),
        ),
    ]
