# Generated by Django 2.2.7 on 2020-05-28 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_adv_app', '0010_auto_20200528_1320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={},
        ),
    ]
