# Generated by Django 2.2.7 on 2020-06-02 07:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('health_adv_app', '0013_auto_20200531_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='generation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
