# Generated by Django 2.2.7 on 2020-06-02 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_adv_app', '0014_auto_20200602_1243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-generation_date']},
        ),
    ]
