# Generated by Django 2.2.7 on 2020-06-02 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_adv_app', '0015_auto_20200602_1245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={},
        ),
        migrations.RemoveField(
            model_name='report',
            name='generation_date',
        ),
    ]
