# Generated by Django 2.2.7 on 2020-06-02 07:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('health_adv_app', '0016_auto_20200602_1300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-generation_date']},
        ),
        migrations.AddField(
            model_name='report',
            name='generation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
